//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APSI_ResevationMod.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_EMPLOYEES_RESERVATION
    {
        public string ProjectCode { get; set; }
        public int EmployeeId { get; set; }
        public int ProjEmplResId { get; set; }
        public int ProjectOwnerId { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Extent { get; set; }
    
        public virtual PROJECT_EMPLOYEES PROJECT_EMPLOYEES { get; set; }
        public virtual PROJECT_EMPLOYEES PROJECT_EMPLOYEES1 { get; set; }
    }
}
