//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APSI_ResevationMod.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_EMPLOYEES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJECT_EMPLOYEES()
        {
            this.PROJECT_EMPLOYEES_RESERVATION = new HashSet<PROJECT_EMPLOYEES_RESERVATION>();
            this.PROJECT_EMPLOYEES_RESERVATION1 = new HashSet<PROJECT_EMPLOYEES_RESERVATION>();
        }
    
        public string ProjectCode { get; set; }
        public int EmployeeId { get; set; }
        public bool ProjectOwner { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PROJECT PROJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_EMPLOYEES_RESERVATION> PROJECT_EMPLOYEES_RESERVATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_EMPLOYEES_RESERVATION> PROJECT_EMPLOYEES_RESERVATION1 { get; set; }
    }
}
