//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APSI_ResevationMod.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESOURCES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESOURCES()
        {
            this.RESOURCES_RESERVATIONS = new HashSet<RESOURCES_RESERVATIONS>();
        }
    
        public int ResourceId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESOURCES_RESERVATIONS> RESOURCES_RESERVATIONS { get; set; }
    }
}
