//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APSI_ResevationMod.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM_RESERVATIONS
    {
        public string RoomCode { get; set; }
        public int RoomResId { get; set; }
        public string ProjectCode { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual EMPLOYEES EMPLOYEES { get; set; }
        public virtual PROJECTS PROJECTS { get; set; }
        public virtual ROOMS ROOMS { get; set; }
    }
}
